### ISSUE TITLE
About the heap usage when generating the RHS

### ISSUE THREAD

**Issue by tingyu66** [barbagroup/fmm-bem-relaxed#3]
I used _massif_ tool in _valgrind_ to monitor the heap usage of StokesBEM running on phantom (for 4 threads). I didn't recorded the stack usage for StokesBEM since it would slow down _valgrind_ a lot for a large problem size (recursions=6).

In the figures below, x-axis shows the number of instructions executed, y-axis gives how much heap memory is used.  

The heap usage peaks when the code is generating RHS. There is an almost doubled memory usage at that point. When I enable _lazy evaluation_, I think it is creating the RHS plan that doubles the memory usage. (line 198 in LaplaceBEM.cpp)

`FMM_plan<kernel_type> rhs_plan = FMM_plan<kernel_type>(K,panels,opts);`

I read the class definition of FMM_plan but could not find where the code needs to allocate extra heap. Would you recall and help me on that? @slayton58 Thanks.

![screen shot 2015-10-07 at 12 38 52 pm](https://cloud.githubusercontent.com/assets/6955356/10401883/e2da81c2-6e8f-11e5-9c01-c0b1c2e2bb12.png)

Here is the stack+heap usage on a smaller case (recursions=4). I found a similar peak. 

![ms_capture](https://cloud.githubusercontent.com/assets/6955356/10402559/1b215afc-6e94-11e5-8ff0-8fe13071c4ea.png)

**Comment by slayton58** [comment]
Generating the RHS plan will always cause the double allocation -- it is literally creating another copy of the tree in order to calculate the matvec that results in the b vector.

The actual allocation will be in the kernel (for instance LaplaceSpherical.hpp, in the init_mulitpole, init_local methods). More allocation can be done when creating the sparse local matrix (include/executor/EvalP2P.hpp, to_matrix method)

**Comment by tingyu66** [comment]
Oh, I see, thanks for the reply
